// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api_model.proto

// The package name determines the name of the directories that truss creates
// for `package Api;` truss will create the directory "Api-service".

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

// one of
type BasicAuth struct {
	User     string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *BasicAuth) Reset()         { *m = BasicAuth{} }
func (m *BasicAuth) String() string { return proto.CompactTextString(m) }
func (*BasicAuth) ProtoMessage()    {}
func (*BasicAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{0}
}
func (m *BasicAuth) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BasicAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BasicAuth.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BasicAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BasicAuth.Merge(m, src)
}
func (m *BasicAuth) XXX_Size() int {
	return m.Size()
}
func (m *BasicAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_BasicAuth.DiscardUnknown(m)
}

var xxx_messageInfo_BasicAuth proto.InternalMessageInfo

func (m *BasicAuth) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *BasicAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type JwtAuth struct {
	User     string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (m *JwtAuth) Reset()         { *m = JwtAuth{} }
func (m *JwtAuth) String() string { return proto.CompactTextString(m) }
func (*JwtAuth) ProtoMessage()    {}
func (*JwtAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{1}
}
func (m *JwtAuth) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *JwtAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_JwtAuth.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *JwtAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JwtAuth.Merge(m, src)
}
func (m *JwtAuth) XXX_Size() int {
	return m.Size()
}
func (m *JwtAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_JwtAuth.DiscardUnknown(m)
}

var xxx_messageInfo_JwtAuth proto.InternalMessageInfo

func (m *JwtAuth) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *JwtAuth) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type OAuth1 struct {
}

func (m *OAuth1) Reset()         { *m = OAuth1{} }
func (m *OAuth1) String() string { return proto.CompactTextString(m) }
func (*OAuth1) ProtoMessage()    {}
func (*OAuth1) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{2}
}
func (m *OAuth1) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OAuth1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OAuth1.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OAuth1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth1.Merge(m, src)
}
func (m *OAuth1) XXX_Size() int {
	return m.Size()
}
func (m *OAuth1) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth1.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth1 proto.InternalMessageInfo

type OAuth2 struct {
}

func (m *OAuth2) Reset()         { *m = OAuth2{} }
func (m *OAuth2) String() string { return proto.CompactTextString(m) }
func (*OAuth2) ProtoMessage()    {}
func (*OAuth2) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{3}
}
func (m *OAuth2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OAuth2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OAuth2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OAuth2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OAuth2.Merge(m, src)
}
func (m *OAuth2) XXX_Size() int {
	return m.Size()
}
func (m *OAuth2) XXX_DiscardUnknown() {
	xxx_messageInfo_OAuth2.DiscardUnknown(m)
}

var xxx_messageInfo_OAuth2 proto.InternalMessageInfo

type ApiModel struct {
	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	UserId      string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// 语法{xxx} 在前端自动替换值到后端
	Url       string            `protobuf:"bytes,13,opt,name=url,proto3" json:"url,omitempty"`
	Headers   map[string]string `protobuf:"bytes,14,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	UrlParams map[string]string `protobuf:"bytes,15,rep,name=url_params,json=urlParams,proto3" json:"url_params,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// 不定义file等二进制类型了
	Body string `protobuf:"bytes,16,opt,name=body,proto3" json:"body,omitempty"`
	// Types that are valid to be assigned to Auth:
	//	*ApiModel_BasicAuth
	//	*ApiModel_JwtAuth
	//	*ApiModel_Oauth1
	//	*ApiModel_Oauth2
	Auth isApiModel_Auth `protobuf_oneof:"auth"`
	// UI 所在目录
	Directories []string `protobuf:"bytes,30,rep,name=directories,proto3" json:"directories,omitempty"`
}

func (m *ApiModel) Reset()         { *m = ApiModel{} }
func (m *ApiModel) String() string { return proto.CompactTextString(m) }
func (*ApiModel) ProtoMessage()    {}
func (*ApiModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{4}
}
func (m *ApiModel) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ApiModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ApiModel.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ApiModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiModel.Merge(m, src)
}
func (m *ApiModel) XXX_Size() int {
	return m.Size()
}
func (m *ApiModel) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiModel.DiscardUnknown(m)
}

var xxx_messageInfo_ApiModel proto.InternalMessageInfo

type isApiModel_Auth interface {
	isApiModel_Auth()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ApiModel_BasicAuth struct {
	BasicAuth *BasicAuth `protobuf:"bytes,17,opt,name=basic_auth,json=basicAuth,proto3,oneof"`
}
type ApiModel_JwtAuth struct {
	JwtAuth *JwtAuth `protobuf:"bytes,18,opt,name=jwt_auth,json=jwtAuth,proto3,oneof"`
}
type ApiModel_Oauth1 struct {
	Oauth1 *OAuth1 `protobuf:"bytes,19,opt,name=oauth1,proto3,oneof"`
}
type ApiModel_Oauth2 struct {
	Oauth2 *OAuth2 `protobuf:"bytes,20,opt,name=oauth2,proto3,oneof"`
}

func (*ApiModel_BasicAuth) isApiModel_Auth() {}
func (*ApiModel_JwtAuth) isApiModel_Auth()   {}
func (*ApiModel_Oauth1) isApiModel_Auth()    {}
func (*ApiModel_Oauth2) isApiModel_Auth()    {}

func (m *ApiModel) GetAuth() isApiModel_Auth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *ApiModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ApiModel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApiModel) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *ApiModel) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ApiModel) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ApiModel) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *ApiModel) GetUrlParams() map[string]string {
	if m != nil {
		return m.UrlParams
	}
	return nil
}

func (m *ApiModel) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *ApiModel) GetBasicAuth() *BasicAuth {
	if x, ok := m.GetAuth().(*ApiModel_BasicAuth); ok {
		return x.BasicAuth
	}
	return nil
}

func (m *ApiModel) GetJwtAuth() *JwtAuth {
	if x, ok := m.GetAuth().(*ApiModel_JwtAuth); ok {
		return x.JwtAuth
	}
	return nil
}

func (m *ApiModel) GetOauth1() *OAuth1 {
	if x, ok := m.GetAuth().(*ApiModel_Oauth1); ok {
		return x.Oauth1
	}
	return nil
}

func (m *ApiModel) GetOauth2() *OAuth2 {
	if x, ok := m.GetAuth().(*ApiModel_Oauth2); ok {
		return x.Oauth2
	}
	return nil
}

func (m *ApiModel) GetDirectories() []string {
	if m != nil {
		return m.Directories
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ApiModel) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ApiModel_OneofMarshaler, _ApiModel_OneofUnmarshaler, _ApiModel_OneofSizer, []interface{}{
		(*ApiModel_BasicAuth)(nil),
		(*ApiModel_JwtAuth)(nil),
		(*ApiModel_Oauth1)(nil),
		(*ApiModel_Oauth2)(nil),
	}
}

func _ApiModel_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ApiModel)
	// auth
	switch x := m.Auth.(type) {
	case *ApiModel_BasicAuth:
		_ = b.EncodeVarint(17<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BasicAuth); err != nil {
			return err
		}
	case *ApiModel_JwtAuth:
		_ = b.EncodeVarint(18<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.JwtAuth); err != nil {
			return err
		}
	case *ApiModel_Oauth1:
		_ = b.EncodeVarint(19<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Oauth1); err != nil {
			return err
		}
	case *ApiModel_Oauth2:
		_ = b.EncodeVarint(20<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Oauth2); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ApiModel.Auth has unexpected type %T", x)
	}
	return nil
}

func _ApiModel_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ApiModel)
	switch tag {
	case 17: // auth.basic_auth
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(BasicAuth)
		err := b.DecodeMessage(msg)
		m.Auth = &ApiModel_BasicAuth{msg}
		return true, err
	case 18: // auth.jwt_auth
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(JwtAuth)
		err := b.DecodeMessage(msg)
		m.Auth = &ApiModel_JwtAuth{msg}
		return true, err
	case 19: // auth.oauth1
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OAuth1)
		err := b.DecodeMessage(msg)
		m.Auth = &ApiModel_Oauth1{msg}
		return true, err
	case 20: // auth.oauth2
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(OAuth2)
		err := b.DecodeMessage(msg)
		m.Auth = &ApiModel_Oauth2{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ApiModel_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ApiModel)
	// auth
	switch x := m.Auth.(type) {
	case *ApiModel_BasicAuth:
		s := proto.Size(x.BasicAuth)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ApiModel_JwtAuth:
		s := proto.Size(x.JwtAuth)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ApiModel_Oauth1:
		s := proto.Size(x.Oauth1)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *ApiModel_Oauth2:
		s := proto.Size(x.Oauth2)
		n += 2 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type CreateApiRequest struct {
	Apis []*ApiModel `protobuf:"bytes,1,rep,name=apis,proto3" json:"apis,omitempty"`
}

func (m *CreateApiRequest) Reset()         { *m = CreateApiRequest{} }
func (m *CreateApiRequest) String() string { return proto.CompactTextString(m) }
func (*CreateApiRequest) ProtoMessage()    {}
func (*CreateApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{5}
}
func (m *CreateApiRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateApiRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApiRequest.Merge(m, src)
}
func (m *CreateApiRequest) XXX_Size() int {
	return m.Size()
}
func (m *CreateApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApiRequest proto.InternalMessageInfo

func (m *CreateApiRequest) GetApis() []*ApiModel {
	if m != nil {
		return m.Apis
	}
	return nil
}

type CreateApiResponse struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (m *CreateApiResponse) Reset()         { *m = CreateApiResponse{} }
func (m *CreateApiResponse) String() string { return proto.CompactTextString(m) }
func (*CreateApiResponse) ProtoMessage()    {}
func (*CreateApiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{6}
}
func (m *CreateApiResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CreateApiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CreateApiResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CreateApiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateApiResponse.Merge(m, src)
}
func (m *CreateApiResponse) XXX_Size() int {
	return m.Size()
}
func (m *CreateApiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateApiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateApiResponse proto.InternalMessageInfo

func (m *CreateApiResponse) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetApiRequest struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (m *GetApiRequest) Reset()         { *m = GetApiRequest{} }
func (m *GetApiRequest) String() string { return proto.CompactTextString(m) }
func (*GetApiRequest) ProtoMessage()    {}
func (*GetApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{7}
}
func (m *GetApiRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetApiRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApiRequest.Merge(m, src)
}
func (m *GetApiRequest) XXX_Size() int {
	return m.Size()
}
func (m *GetApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetApiRequest proto.InternalMessageInfo

func (m *GetApiRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

type GetApiResponse struct {
	Apis []*ApiModel `protobuf:"bytes,1,rep,name=Apis,proto3" json:"Apis,omitempty"`
}

func (m *GetApiResponse) Reset()         { *m = GetApiResponse{} }
func (m *GetApiResponse) String() string { return proto.CompactTextString(m) }
func (*GetApiResponse) ProtoMessage()    {}
func (*GetApiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{8}
}
func (m *GetApiResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GetApiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GetApiResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GetApiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetApiResponse.Merge(m, src)
}
func (m *GetApiResponse) XXX_Size() int {
	return m.Size()
}
func (m *GetApiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetApiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetApiResponse proto.InternalMessageInfo

func (m *GetApiResponse) GetApis() []*ApiModel {
	if m != nil {
		return m.Apis
	}
	return nil
}

type ListApiRequest struct {
	Header      int32 `protobuf:"varint,1,opt,name=header,proto3" json:"header,omitempty"`
	CurrentPage int32 `protobuf:"varint,9,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	PageSize    int32 `protobuf:"varint,10,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (m *ListApiRequest) Reset()         { *m = ListApiRequest{} }
func (m *ListApiRequest) String() string { return proto.CompactTextString(m) }
func (*ListApiRequest) ProtoMessage()    {}
func (*ListApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{9}
}
func (m *ListApiRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListApiRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApiRequest.Merge(m, src)
}
func (m *ListApiRequest) XXX_Size() int {
	return m.Size()
}
func (m *ListApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListApiRequest proto.InternalMessageInfo

func (m *ListApiRequest) GetHeader() int32 {
	if m != nil {
		return m.Header
	}
	return 0
}

func (m *ListApiRequest) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ListApiRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListApiResponse struct {
	Headers []*KV       `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	Apis    []*ApiModel `protobuf:"bytes,2,rep,name=Apis,proto3" json:"Apis,omitempty"`
}

func (m *ListApiResponse) Reset()         { *m = ListApiResponse{} }
func (m *ListApiResponse) String() string { return proto.CompactTextString(m) }
func (*ListApiResponse) ProtoMessage()    {}
func (*ListApiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{10}
}
func (m *ListApiResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ListApiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ListApiResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ListApiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListApiResponse.Merge(m, src)
}
func (m *ListApiResponse) XXX_Size() int {
	return m.Size()
}
func (m *ListApiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListApiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListApiResponse proto.InternalMessageInfo

func (m *ListApiResponse) GetHeaders() []*KV {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *ListApiResponse) GetApis() []*ApiModel {
	if m != nil {
		return m.Apis
	}
	return nil
}

type UpdateApiRequest struct {
	Apis []*ApiModel `protobuf:"bytes,1,rep,name=Apis,proto3" json:"Apis,omitempty"`
}

func (m *UpdateApiRequest) Reset()         { *m = UpdateApiRequest{} }
func (m *UpdateApiRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateApiRequest) ProtoMessage()    {}
func (*UpdateApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{11}
}
func (m *UpdateApiRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *UpdateApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_UpdateApiRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *UpdateApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateApiRequest.Merge(m, src)
}
func (m *UpdateApiRequest) XXX_Size() int {
	return m.Size()
}
func (m *UpdateApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateApiRequest proto.InternalMessageInfo

func (m *UpdateApiRequest) GetApis() []*ApiModel {
	if m != nil {
		return m.Apis
	}
	return nil
}

type DeleteApiRequest struct {
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (m *DeleteApiRequest) Reset()         { *m = DeleteApiRequest{} }
func (m *DeleteApiRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteApiRequest) ProtoMessage()    {}
func (*DeleteApiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27a3320a6e8e11d1, []int{12}
}
func (m *DeleteApiRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeleteApiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeleteApiRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeleteApiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteApiRequest.Merge(m, src)
}
func (m *DeleteApiRequest) XXX_Size() int {
	return m.Size()
}
func (m *DeleteApiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteApiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteApiRequest proto.InternalMessageInfo

func (m *DeleteApiRequest) GetIds() []string {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*BasicAuth)(nil), "pb.BasicAuth")
	proto.RegisterType((*JwtAuth)(nil), "pb.JwtAuth")
	proto.RegisterType((*OAuth1)(nil), "pb.OAuth1")
	proto.RegisterType((*OAuth2)(nil), "pb.OAuth2")
	proto.RegisterType((*ApiModel)(nil), "pb.ApiModel")
	proto.RegisterMapType((map[string]string)(nil), "pb.ApiModel.HeadersEntry")
	proto.RegisterMapType((map[string]string)(nil), "pb.ApiModel.UrlParamsEntry")
	proto.RegisterType((*CreateApiRequest)(nil), "pb.CreateApiRequest")
	proto.RegisterType((*CreateApiResponse)(nil), "pb.CreateApiResponse")
	proto.RegisterType((*GetApiRequest)(nil), "pb.GetApiRequest")
	proto.RegisterType((*GetApiResponse)(nil), "pb.GetApiResponse")
	proto.RegisterType((*ListApiRequest)(nil), "pb.ListApiRequest")
	proto.RegisterType((*ListApiResponse)(nil), "pb.ListApiResponse")
	proto.RegisterType((*UpdateApiRequest)(nil), "pb.UpdateApiRequest")
	proto.RegisterType((*DeleteApiRequest)(nil), "pb.DeleteApiRequest")
}

func init() { proto.RegisterFile("api_model.proto", fileDescriptor_27a3320a6e8e11d1) }

var fileDescriptor_27a3320a6e8e11d1 = []byte{
	// 624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x8d, 0x93, 0xd4, 0x89, 0x27, 0x69, 0x9a, 0x2e, 0x15, 0x2c, 0xa9, 0x64, 0xb9, 0x56, 0x91,
	0x72, 0x8a, 0x54, 0xb7, 0x07, 0x28, 0x5c, 0x52, 0x40, 0x84, 0x2f, 0x51, 0x19, 0x95, 0x6b, 0xb4,
	0x89, 0x57, 0xcd, 0x96, 0x24, 0x5e, 0x76, 0xd7, 0x54, 0xed, 0xaf, 0xe0, 0x67, 0x21, 0x4e, 0x3d,
	0x72, 0x44, 0xed, 0x1f, 0x41, 0xbb, 0xfe, 0xa8, 0x4b, 0x55, 0x21, 0xb8, 0xcd, 0xcc, 0x7b, 0x6f,
	0x76, 0x66, 0x9e, 0x65, 0x58, 0x23, 0x9c, 0x8d, 0x17, 0x71, 0x44, 0xe7, 0x03, 0x2e, 0x62, 0x15,
	0xa3, 0x2a, 0x9f, 0xf4, 0xda, 0xd3, 0x78, 0xb1, 0x88, 0x97, 0x69, 0xc5, 0x7f, 0x0a, 0xce, 0x01,
	0x91, 0x6c, 0x3a, 0x4c, 0xd4, 0x0c, 0x21, 0xa8, 0x27, 0x92, 0x0a, 0x6c, 0x79, 0x56, 0xdf, 0x09,
	0x4d, 0x8c, 0x7a, 0xd0, 0xe4, 0x44, 0xca, 0xd3, 0x58, 0x44, 0xb8, 0x6a, 0xea, 0x45, 0xee, 0x3f,
	0x81, 0xc6, 0x9b, 0x53, 0xf5, 0x5f, 0xd2, 0x26, 0xd8, 0x1f, 0xb4, 0x70, 0xa7, 0x88, 0x02, 0xff,
	0x47, 0x1d, 0x9a, 0x43, 0xce, 0xde, 0xeb, 0x81, 0x51, 0x07, 0xaa, 0x2c, 0xca, 0xda, 0x55, 0x59,
	0xa4, 0x1f, 0x58, 0x92, 0x05, 0xcd, 0x1a, 0x99, 0x18, 0x79, 0xd0, 0x8a, 0xa8, 0x9c, 0x0a, 0xc6,
	0x15, 0x8b, 0x97, 0xb8, 0x66, 0xa0, 0x72, 0x09, 0x3d, 0x80, 0x86, 0x1e, 0x65, 0xcc, 0x22, 0x5c,
	0x37, 0xa8, 0xad, 0xd3, 0xd7, 0x11, 0xea, 0x42, 0x2d, 0x11, 0x73, 0xbc, 0x6a, 0x8a, 0x3a, 0x44,
	0xbb, 0xd0, 0x98, 0x51, 0x12, 0x51, 0x21, 0x71, 0xc7, 0xab, 0xf5, 0x5b, 0xc1, 0xc3, 0x01, 0x9f,
	0x0c, 0xf2, 0x79, 0x06, 0xa3, 0x14, 0x7b, 0xb9, 0x54, 0xe2, 0x2c, 0xcc, 0x99, 0x68, 0x1f, 0x20,
	0x11, 0xf3, 0x31, 0x27, 0x82, 0x2c, 0x24, 0x5e, 0x33, 0xba, 0xcd, 0x1b, 0xba, 0x23, 0x31, 0x3f,
	0x34, 0x68, 0xaa, 0x74, 0x92, 0x3c, 0xd7, 0x1b, 0x4d, 0xe2, 0xe8, 0x0c, 0x77, 0xd3, 0x8d, 0x74,
	0x8c, 0x06, 0x00, 0x13, 0x6d, 0xc7, 0x98, 0x24, 0x6a, 0x86, 0xd7, 0x3d, 0xab, 0xdf, 0x0a, 0x56,
	0x75, 0xbf, 0xc2, 0xa4, 0x51, 0x25, 0x74, 0x26, 0x85, 0x63, 0x7d, 0x68, 0x9e, 0x9c, 0xaa, 0x94,
	0x8d, 0x0c, 0xbb, 0xa5, 0xd9, 0x99, 0x2b, 0xa3, 0x4a, 0xd8, 0x38, 0xc9, 0x0c, 0xda, 0x06, 0x3b,
	0xd6, 0xb4, 0x1d, 0x7c, 0xcf, 0xf0, 0x40, 0xf3, 0x52, 0x0b, 0x46, 0x95, 0x30, 0xc3, 0x0a, 0x56,
	0x80, 0x37, 0xfe, 0x60, 0x05, 0x05, 0x2b, 0x30, 0x77, 0x67, 0x82, 0x4e, 0x55, 0x2c, 0x18, 0x95,
	0xd8, 0xf5, 0x6a, 0xe6, 0xee, 0xd7, 0xa5, 0xde, 0x3e, 0xb4, 0xcb, 0x07, 0xd3, 0xe7, 0xfe, 0x4c,
	0xcf, 0x32, 0x3b, 0x75, 0x88, 0x36, 0x60, 0xe5, 0x2b, 0x99, 0x27, 0xb9, 0xa1, 0x69, 0xb2, 0x5f,
	0x7d, 0x6c, 0xf5, 0x9e, 0x41, 0xe7, 0xe6, 0xd1, 0xfe, 0x45, 0x7d, 0x60, 0x43, 0x5d, 0x0f, 0xe9,
	0xef, 0x41, 0xf7, 0xb9, 0xa0, 0x44, 0xd1, 0x21, 0x67, 0x21, 0xfd, 0x92, 0x50, 0xa9, 0x90, 0x07,
	0x75, 0xc2, 0x99, 0xc4, 0x96, 0xf1, 0xa9, 0x5d, 0xf6, 0x29, 0x34, 0x88, 0xff, 0x08, 0xd6, 0x4b,
	0x2a, 0xc9, 0xe3, 0xa5, 0xa4, 0xfa, 0x79, 0x16, 0xa5, 0x2a, 0x27, 0xd4, 0xa1, 0xbf, 0x05, 0xab,
	0xaf, 0xa8, 0x2a, 0x75, 0xbe, 0x4d, 0x09, 0xa0, 0x93, 0x53, 0xb2, 0x36, 0x1e, 0xd4, 0x87, 0x77,
	0xbe, 0xae, 0x11, 0x7f, 0x06, 0x9d, 0x77, 0x4c, 0x96, 0xfb, 0xde, 0x07, 0x3b, 0xfd, 0xd4, 0xcc,
	0xf2, 0x2b, 0x61, 0x96, 0xa1, 0x2d, 0x68, 0x4f, 0x13, 0x21, 0xe8, 0x52, 0x8d, 0x39, 0x39, 0xa6,
	0xd8, 0x31, 0x68, 0x2b, 0xab, 0x1d, 0x92, 0x63, 0x8a, 0x36, 0xc1, 0xd1, 0xd0, 0x58, 0xb2, 0x73,
	0x8a, 0xc1, 0xe0, 0x4d, 0x5d, 0xf8, 0xc8, 0xce, 0xa9, 0x7f, 0x04, 0x6b, 0xc5, 0x4b, 0xc5, 0x78,
	0xc5, 0xf7, 0x9f, 0x4e, 0x68, 0xeb, 0x09, 0xdf, 0x7e, 0xba, 0xfe, 0xd8, 0xf3, 0x05, 0xaa, 0x77,
	0x2e, 0xb0, 0x07, 0xdd, 0x23, 0x1e, 0xdd, 0x3a, 0xfa, 0x5f, 0xd6, 0xde, 0x86, 0xee, 0x0b, 0x3a,
	0xa7, 0x37, 0x54, 0xb7, 0x0e, 0x7a, 0x80, 0xbf, 0x5f, 0xba, 0xd6, 0xc5, 0xa5, 0x6b, 0xfd, 0xba,
	0x74, 0xad, 0x6f, 0x57, 0x6e, 0xe5, 0xe2, 0xca, 0xad, 0xfc, 0xbc, 0x72, 0x2b, 0x13, 0xdb, 0xfc,
	0xca, 0x76, 0x7f, 0x07, 0x00, 0x00, 0xff, 0xff, 0x4b, 0xd1, 0xb2, 0x27, 0xef, 0x04, 0x00, 0x00,
}

func (m *BasicAuth) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BasicAuth) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.User)))
		i += copy(dAtA[i:], m.User)
	}
	if len(m.Password) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.Password)))
		i += copy(dAtA[i:], m.Password)
	}
	return i, nil
}

func (m *JwtAuth) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *JwtAuth) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.User) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.User)))
		i += copy(dAtA[i:], m.User)
	}
	if len(m.Password) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.Password)))
		i += copy(dAtA[i:], m.Password)
	}
	return i, nil
}

func (m *OAuth1) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OAuth1) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *OAuth2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OAuth2) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	return i, nil
}

func (m *ApiModel) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ApiModel) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.Id)))
		i += copy(dAtA[i:], m.Id)
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.Description) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.Description)))
		i += copy(dAtA[i:], m.Description)
	}
	if len(m.UserId) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.UserId)))
		i += copy(dAtA[i:], m.UserId)
	}
	if len(m.Url) > 0 {
		dAtA[i] = 0x6a
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.Url)))
		i += copy(dAtA[i:], m.Url)
	}
	if len(m.Headers) > 0 {
		for k, _ := range m.Headers {
			dAtA[i] = 0x72
			i++
			v := m.Headers[k]
			mapSize := 1 + len(k) + sovApiModel(uint64(len(k))) + 1 + len(v) + sovApiModel(uint64(len(v)))
			i = encodeVarintApiModel(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintApiModel(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintApiModel(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.UrlParams) > 0 {
		for k, _ := range m.UrlParams {
			dAtA[i] = 0x7a
			i++
			v := m.UrlParams[k]
			mapSize := 1 + len(k) + sovApiModel(uint64(len(k))) + 1 + len(v) + sovApiModel(uint64(len(v)))
			i = encodeVarintApiModel(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintApiModel(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintApiModel(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if len(m.Body) > 0 {
		dAtA[i] = 0x82
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(len(m.Body)))
		i += copy(dAtA[i:], m.Body)
	}
	if m.Auth != nil {
		nn1, err1 := m.Auth.MarshalTo(dAtA[i:])
		if err1 != nil {
			return 0, err1
		}
		i += nn1
	}
	if len(m.Directories) > 0 {
		for _, s := range m.Directories {
			dAtA[i] = 0xf2
			i++
			dAtA[i] = 0x1
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *ApiModel_BasicAuth) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.BasicAuth != nil {
		dAtA[i] = 0x8a
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(m.BasicAuth.Size()))
		n2, err2 := m.BasicAuth.MarshalTo(dAtA[i:])
		if err2 != nil {
			return 0, err2
		}
		i += n2
	}
	return i, nil
}
func (m *ApiModel_JwtAuth) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.JwtAuth != nil {
		dAtA[i] = 0x92
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(m.JwtAuth.Size()))
		n3, err3 := m.JwtAuth.MarshalTo(dAtA[i:])
		if err3 != nil {
			return 0, err3
		}
		i += n3
	}
	return i, nil
}
func (m *ApiModel_Oauth1) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Oauth1 != nil {
		dAtA[i] = 0x9a
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(m.Oauth1.Size()))
		n4, err4 := m.Oauth1.MarshalTo(dAtA[i:])
		if err4 != nil {
			return 0, err4
		}
		i += n4
	}
	return i, nil
}
func (m *ApiModel_Oauth2) MarshalTo(dAtA []byte) (int, error) {
	i := 0
	if m.Oauth2 != nil {
		dAtA[i] = 0xa2
		i++
		dAtA[i] = 0x1
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(m.Oauth2.Size()))
		n5, err5 := m.Oauth2.MarshalTo(dAtA[i:])
		if err5 != nil {
			return 0, err5
		}
		i += n5
	}
	return i, nil
}
func (m *CreateApiRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateApiRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Apis) > 0 {
		for _, msg := range m.Apis {
			dAtA[i] = 0xa
			i++
			i = encodeVarintApiModel(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *CreateApiResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CreateApiResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for _, s := range m.Ids {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *GetApiRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetApiRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for _, s := range m.Ids {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func (m *GetApiResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GetApiResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Apis) > 0 {
		for _, msg := range m.Apis {
			dAtA[i] = 0xa
			i++
			i = encodeVarintApiModel(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *ListApiRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListApiRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Header != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(m.Header))
	}
	if m.CurrentPage != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(m.CurrentPage))
	}
	if m.PageSize != 0 {
		dAtA[i] = 0x50
		i++
		i = encodeVarintApiModel(dAtA, i, uint64(m.PageSize))
	}
	return i, nil
}

func (m *ListApiResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ListApiResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Headers) > 0 {
		for _, msg := range m.Headers {
			dAtA[i] = 0xa
			i++
			i = encodeVarintApiModel(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Apis) > 0 {
		for _, msg := range m.Apis {
			dAtA[i] = 0x12
			i++
			i = encodeVarintApiModel(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *UpdateApiRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *UpdateApiRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Apis) > 0 {
		for _, msg := range m.Apis {
			dAtA[i] = 0xa
			i++
			i = encodeVarintApiModel(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *DeleteApiRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeleteApiRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for _, s := range m.Ids {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	return i, nil
}

func encodeVarintApiModel(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *BasicAuth) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovApiModel(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovApiModel(uint64(l))
	}
	return n
}

func (m *JwtAuth) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.User)
	if l > 0 {
		n += 1 + l + sovApiModel(uint64(l))
	}
	l = len(m.Password)
	if l > 0 {
		n += 1 + l + sovApiModel(uint64(l))
	}
	return n
}

func (m *OAuth1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *OAuth2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *ApiModel) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovApiModel(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovApiModel(uint64(l))
	}
	l = len(m.Description)
	if l > 0 {
		n += 1 + l + sovApiModel(uint64(l))
	}
	l = len(m.UserId)
	if l > 0 {
		n += 1 + l + sovApiModel(uint64(l))
	}
	l = len(m.Url)
	if l > 0 {
		n += 1 + l + sovApiModel(uint64(l))
	}
	if len(m.Headers) > 0 {
		for k, v := range m.Headers {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovApiModel(uint64(len(k))) + 1 + len(v) + sovApiModel(uint64(len(v)))
			n += mapEntrySize + 1 + sovApiModel(uint64(mapEntrySize))
		}
	}
	if len(m.UrlParams) > 0 {
		for k, v := range m.UrlParams {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovApiModel(uint64(len(k))) + 1 + len(v) + sovApiModel(uint64(len(v)))
			n += mapEntrySize + 1 + sovApiModel(uint64(mapEntrySize))
		}
	}
	l = len(m.Body)
	if l > 0 {
		n += 2 + l + sovApiModel(uint64(l))
	}
	if m.Auth != nil {
		n += m.Auth.Size()
	}
	if len(m.Directories) > 0 {
		for _, s := range m.Directories {
			l = len(s)
			n += 2 + l + sovApiModel(uint64(l))
		}
	}
	return n
}

func (m *ApiModel_BasicAuth) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BasicAuth != nil {
		l = m.BasicAuth.Size()
		n += 2 + l + sovApiModel(uint64(l))
	}
	return n
}
func (m *ApiModel_JwtAuth) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.JwtAuth != nil {
		l = m.JwtAuth.Size()
		n += 2 + l + sovApiModel(uint64(l))
	}
	return n
}
func (m *ApiModel_Oauth1) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Oauth1 != nil {
		l = m.Oauth1.Size()
		n += 2 + l + sovApiModel(uint64(l))
	}
	return n
}
func (m *ApiModel_Oauth2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Oauth2 != nil {
		l = m.Oauth2.Size()
		n += 2 + l + sovApiModel(uint64(l))
	}
	return n
}
func (m *CreateApiRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Apis) > 0 {
		for _, e := range m.Apis {
			l = e.Size()
			n += 1 + l + sovApiModel(uint64(l))
		}
	}
	return n
}

func (m *CreateApiResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for _, s := range m.Ids {
			l = len(s)
			n += 1 + l + sovApiModel(uint64(l))
		}
	}
	return n
}

func (m *GetApiRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for _, s := range m.Ids {
			l = len(s)
			n += 1 + l + sovApiModel(uint64(l))
		}
	}
	return n
}

func (m *GetApiResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Apis) > 0 {
		for _, e := range m.Apis {
			l = e.Size()
			n += 1 + l + sovApiModel(uint64(l))
		}
	}
	return n
}

func (m *ListApiRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Header != 0 {
		n += 1 + sovApiModel(uint64(m.Header))
	}
	if m.CurrentPage != 0 {
		n += 1 + sovApiModel(uint64(m.CurrentPage))
	}
	if m.PageSize != 0 {
		n += 1 + sovApiModel(uint64(m.PageSize))
	}
	return n
}

func (m *ListApiResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Headers) > 0 {
		for _, e := range m.Headers {
			l = e.Size()
			n += 1 + l + sovApiModel(uint64(l))
		}
	}
	if len(m.Apis) > 0 {
		for _, e := range m.Apis {
			l = e.Size()
			n += 1 + l + sovApiModel(uint64(l))
		}
	}
	return n
}

func (m *UpdateApiRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Apis) > 0 {
		for _, e := range m.Apis {
			l = e.Size()
			n += 1 + l + sovApiModel(uint64(l))
		}
	}
	return n
}

func (m *DeleteApiRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ids) > 0 {
		for _, s := range m.Ids {
			l = len(s)
			n += 1 + l + sovApiModel(uint64(l))
		}
	}
	return n
}

func sovApiModel(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApiModel(x uint64) (n int) {
	return sovApiModel(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BasicAuth) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BasicAuth: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BasicAuth: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *JwtAuth) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: JwtAuth: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: JwtAuth: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field User", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.User = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Password", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Password = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OAuth1) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OAuth1: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OAuth1: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OAuth2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OAuth2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OAuth2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ApiModel) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ApiModel: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ApiModel: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Description", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Description = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 13:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Url", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Url = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Headers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Headers == nil {
				m.Headers = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowApiModel
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowApiModel
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthApiModel
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthApiModel
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowApiModel
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthApiModel
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthApiModel
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipApiModel(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthApiModel
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Headers[mapkey] = mapvalue
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UrlParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.UrlParams == nil {
				m.UrlParams = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowApiModel
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowApiModel
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthApiModel
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthApiModel
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowApiModel
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthApiModel
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthApiModel
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipApiModel(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthApiModel
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.UrlParams[mapkey] = mapvalue
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Body", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Body = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 17:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BasicAuth", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &BasicAuth{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Auth = &ApiModel_BasicAuth{v}
			iNdEx = postIndex
		case 18:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JwtAuth", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &JwtAuth{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Auth = &ApiModel_JwtAuth{v}
			iNdEx = postIndex
		case 19:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oauth1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &OAuth1{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Auth = &ApiModel_Oauth1{v}
			iNdEx = postIndex
		case 20:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Oauth2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &OAuth2{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Auth = &ApiModel_Oauth2{v}
			iNdEx = postIndex
		case 30:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Directories", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Directories = append(m.Directories, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateApiRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateApiRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateApiRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Apis = append(m.Apis, &ApiModel{})
			if err := m.Apis[len(m.Apis)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CreateApiResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CreateApiResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CreateApiResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ids", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ids = append(m.Ids, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetApiRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetApiRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetApiRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ids", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ids = append(m.Ids, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GetApiResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GetApiResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GetApiResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Apis = append(m.Apis, &ApiModel{})
			if err := m.Apis[len(m.Apis)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListApiRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListApiRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListApiRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			m.Header = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Header |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentPage", wireType)
			}
			m.CurrentPage = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentPage |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PageSize", wireType)
			}
			m.PageSize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PageSize |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ListApiResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ListApiResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ListApiResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Headers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Headers = append(m.Headers, &KV{})
			if err := m.Headers[len(m.Headers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Apis = append(m.Apis, &ApiModel{})
			if err := m.Apis[len(m.Apis)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *UpdateApiRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: UpdateApiRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: UpdateApiRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Apis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Apis = append(m.Apis, &ApiModel{})
			if err := m.Apis[len(m.Apis)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeleteApiRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeleteApiRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeleteApiRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ids", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApiModel
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApiModel
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ids = append(m.Ids, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApiModel(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApiModel
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApiModel(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApiModel
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApiModel
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApiModel
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthApiModel
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowApiModel
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipApiModel(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthApiModel
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthApiModel = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApiModel   = fmt.Errorf("proto: integer overflow")
)
