// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: member_service.proto

// The package name determines the name of the directories that truss creates
// for `package api;` truss will create the directory "api-service".

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/metaverse/truss/deftree/googlethirdparty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("member_service.proto", fileDescriptor_41355fb489f7b05a) }

var fileDescriptor_41355fb489f7b05a = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x4b, 0xe3, 0x40,
	0x18, 0xc6, 0x9b, 0xb6, 0xe4, 0x30, 0xec, 0xb2, 0xec, 0x6c, 0xb3, 0x2d, 0x59, 0xc8, 0xa1, 0xa7,
	0xa5, 0x87, 0x0c, 0xbb, 0xde, 0xbc, 0x59, 0x5b, 0x14, 0x54, 0x44, 0xa1, 0x17, 0x2f, 0x92, 0x3f,
	0xaf, 0x69, 0x24, 0x93, 0x89, 0x33, 0x6f, 0x0a, 0x45, 0xbc, 0xf8, 0x09, 0x04, 0x3f, 0x8c, 0x5f,
	0xc1, 0x63, 0xc1, 0x8b, 0x47, 0x69, 0xfd, 0x20, 0xd2, 0x49, 0x2c, 0x24, 0x0a, 0xde, 0x9e, 0x3c,
	0x0f, 0xef, 0xef, 0x09, 0xcf, 0x90, 0x0e, 0x07, 0xee, 0x83, 0x3c, 0x57, 0x20, 0x67, 0x71, 0x00,
	0x6e, 0x26, 0x05, 0x0a, 0xda, 0xcc, 0x7c, 0x7b, 0x1c, 0xc5, 0x38, 0xcd, 0x7d, 0x37, 0x10, 0x9c,
	0x71, 0x40, 0x6f, 0x06, 0x52, 0x01, 0x43, 0x99, 0x2b, 0xc5, 0x42, 0xb8, 0x40, 0x09, 0xc0, 0x22,
	0x21, 0xa2, 0x04, 0x70, 0x1a, 0xcb, 0x30, 0xf3, 0x24, 0xce, 0x99, 0x97, 0xa6, 0x02, 0x3d, 0x8c,
	0x45, 0xaa, 0x0a, 0x94, 0xfd, 0x2d, 0x10, 0x9c, 0x8b, 0xb4, 0xfc, 0xa2, 0x65, 0x1d, 0x17, 0x21,
	0x24, 0x85, 0xf7, 0xff, 0xa1, 0x45, 0xcc, 0x23, 0x6d, 0xd3, 0x09, 0x31, 0x03, 0x09, 0x1e, 0x02,
	0xed, 0xba, 0x99, 0xef, 0xee, 0x6a, 0x5d, 0x64, 0xa7, 0x70, 0x95, 0x83, 0x42, 0xbb, 0xf7, 0x31,
	0x50, 0x99, 0x48, 0x15, 0xf4, 0x7b, 0xb7, 0x4f, 0xaf, 0xf7, 0x4d, 0xda, 0xff, 0xce, 0x2e, 0x43,
	0x36, 0xfb, 0xc7, 0x8a, 0xaa, 0x6d, 0x63, 0x40, 0x8f, 0x49, 0x2b, 0x02, 0xa4, 0x9d, 0xf5, 0xe9,
	0x1e, 0x60, 0x15, 0x68, 0xd5, 0xdc, 0x92, 0xf6, 0x47, 0xd3, 0x2c, 0xfa, 0xab, 0x42, 0x63, 0xd7,
	0x71, 0xa8, 0x6e, 0x28, 0x90, 0x76, 0x12, 0x2b, 0xa4, 0xfa, 0xf6, 0x30, 0x56, 0x35, 0xe4, 0xef,
	0xba, 0x5d, 0x32, 0x5d, 0xcd, 0xfc, 0x4b, 0xab, 0x7f, 0x78, 0xd6, 0x1d, 0x5a, 0xa4, 0xbd, 0x3f,
	0xde, 0x19, 0xd5, 0x02, 0x7a, 0x40, 0xcc, 0x3c, 0x0b, 0x37, 0x73, 0x4c, 0xb4, 0xae, 0x56, 0xfd,
	0x5c, 0x07, 0x63, 0x9e, 0xe1, 0x7c, 0xd3, 0x62, 0xe9, 0x96, 0x1f, 0x76, 0x0d, 0x76, 0x42, 0xcc,
	0x10, 0x12, 0x78, 0x87, 0x8d, 0xb4, 0xfe, 0x12, 0x56, 0xce, 0x30, 0xf8, 0x6c, 0x86, 0x61, 0xef,
	0x71, 0xe9, 0x18, 0x8b, 0xa5, 0x63, 0xbc, 0x2c, 0x1d, 0xe3, 0x6e, 0xe5, 0x34, 0x16, 0x2b, 0xa7,
	0xf1, 0xbc, 0x72, 0x1a, 0xbe, 0xa9, 0x9f, 0x76, 0xeb, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x58, 0x29,
	0x96, 0xbf, 0x5f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MemberClient is the client API for Member service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MemberClient interface {
	Create(ctx context.Context, in *CreateMemberRequest, opts ...grpc.CallOption) (*CreateMemberResponse, error)
	Get(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error)
	List(ctx context.Context, in *ListMemberRequest, opts ...grpc.CallOption) (*ListMemberResponse, error)
	Update(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
	Delete(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*EmptyResponse, error)
}

type memberClient struct {
	cc *grpc.ClientConn
}

func NewMemberClient(cc *grpc.ClientConn) MemberClient {
	return &memberClient{cc}
}

func (c *memberClient) Create(ctx context.Context, in *CreateMemberRequest, opts ...grpc.CallOption) (*CreateMemberResponse, error) {
	out := new(CreateMemberResponse)
	err := c.cc.Invoke(ctx, "/pb.Member/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) Get(ctx context.Context, in *GetMemberRequest, opts ...grpc.CallOption) (*GetMemberResponse, error) {
	out := new(GetMemberResponse)
	err := c.cc.Invoke(ctx, "/pb.Member/get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) List(ctx context.Context, in *ListMemberRequest, opts ...grpc.CallOption) (*ListMemberResponse, error) {
	out := new(ListMemberResponse)
	err := c.cc.Invoke(ctx, "/pb.Member/list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) Update(ctx context.Context, in *UpdateMemberRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/pb.Member/update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberClient) Delete(ctx context.Context, in *DeleteMemberRequest, opts ...grpc.CallOption) (*EmptyResponse, error) {
	out := new(EmptyResponse)
	err := c.cc.Invoke(ctx, "/pb.Member/delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServer is the server API for Member service.
type MemberServer interface {
	Create(context.Context, *CreateMemberRequest) (*CreateMemberResponse, error)
	Get(context.Context, *GetMemberRequest) (*GetMemberResponse, error)
	List(context.Context, *ListMemberRequest) (*ListMemberResponse, error)
	Update(context.Context, *UpdateMemberRequest) (*EmptyResponse, error)
	Delete(context.Context, *DeleteMemberRequest) (*EmptyResponse, error)
}

// UnimplementedMemberServer can be embedded to have forward compatible implementations.
type UnimplementedMemberServer struct {
}

func (*UnimplementedMemberServer) Create(ctx context.Context, req *CreateMemberRequest) (*CreateMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedMemberServer) Get(ctx context.Context, req *GetMemberRequest) (*GetMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedMemberServer) List(ctx context.Context, req *ListMemberRequest) (*ListMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedMemberServer) Update(ctx context.Context, req *UpdateMemberRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedMemberServer) Delete(ctx context.Context, req *DeleteMemberRequest) (*EmptyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterMemberServer(s *grpc.Server, srv MemberServer) {
	s.RegisterService(&_Member_serviceDesc, srv)
}

func _Member_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Member/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).Create(ctx, req.(*CreateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Member/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).Get(ctx, req.(*GetMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Member/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).List(ctx, req.(*ListMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Member/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).Update(ctx, req.(*UpdateMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Member_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Member/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServer).Delete(ctx, req.(*DeleteMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Member_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Member",
	HandlerType: (*MemberServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _Member_Create_Handler,
		},
		{
			MethodName: "get",
			Handler:    _Member_Get_Handler,
		},
		{
			MethodName: "list",
			Handler:    _Member_List_Handler,
		},
		{
			MethodName: "update",
			Handler:    _Member_Update_Handler,
		},
		{
			MethodName: "delete",
			Handler:    _Member_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "member_service.proto",
}
